### ISSUE TITLE
Implement `Trace` and `Finalize` traits in features

### ISSUE THREAD

**Issue by neeldug** [tkaitchuck/aHash#44] opened 2020-08-25 21:29 UTC
Currently, having an issue with using aHash with usage in [rust-gc](https://github.com/Manishearth/rust-gc), an issue has been raised with adding support for more crates usage, which in turn states that this should be added as a feature in these other crates, currently using FxHash, which incorporates STL and so works with the gc's STL Traits, however, this does not occur with aHash. 

This also links to #42 as the trait implementation is due to this.

**Comment by tkaitchuck** [comment] 2020-08-26 02:09
@neeldug What do you propose?

**Comment by neeldug** [comment] 2020-08-26 02:29
I propose that a feature be added which enables this Trait for gc, similar to how it’s implemented for STL collections, i.e. Hashmap and Hashset, which can be found [here](https://github.com/Manishearth/rust-gc/blob/563f685972d98d3608b52a82bbfef811d89abc54/gc/src/trace.rs#L340). I’m unsure to the specifics of implementing a feature in crates, however, I’ll have a quick look.

**Comment by tkaitchuck** [comment] 2020-08-27 14:29
By the orphan rules, the trait impl must either live in aHash code in which case aHash would need a dependency on rust-gc (which is understandable because most users of aHash aren't using rust-gc). Or it could live in rust-gc and rust-gc could depend on aHash.

I think the later probably makes more sense.

I would love to get traits like this auto derived as discussed in #42 but I don't know how to do that and preserve the constructors. If you can think of a way I would be happy to hear it.

**Comment by neeldug** [comment] 2020-08-27 14:47
I understand what you mean by preserving constructors but isn’t it at all possible to create a gc feature with the optional dependency of rust-gc and add a trait impl for the feature itself?

**Comment by neeldug** [comment] 2020-09-03 18:07
Actually @tkaitchuck, just realised exactly what you meant by this, however, couldn't it be possible to use features and modify the constructor based on the feature that's active? By using the `cfg!` macro. However, I haven't had a specific look at the constructors and whether or not this would be feasible.

**Comment by tkaitchuck** [comment] 2020-09-03 23:20
The problem is actually deeper than that. If we did an alias then when someone imported AHashMap and tried to call new, it would call https://doc.rust-lang.org/beta/std/collections/struct.HashMap.html#method.new
But it is hardcoded to RandomState which is tied to the default hasher. So they would get a standard hashmap, and might not notice that they in-fact are importing aHash only to not use it.

If we could modify the standard library we could fix this, but baring that, we need a way to define a different version of `new`. If it were on a trait, that would be easy, but its a struct. So the only thing we can do is make another struct that has a method also named "new". 

I would also love it, if I could declare that: "this struct implements all the traits this other struct implements by delegating to it". However that currently is not expressible within the type system. (There is quite a bit of discussion on how to add this on internals.rust-lang.org, and even an RFC. But it's not going to land very soon)

Normally when I encounter this sort of problem I reach for [shrinkwraprs](https://docs.rs/shrinkwraprs/0.3.0/shrinkwraprs/) and let deref take care of it automatically. There are a few cases where that doesn't work, and you and #42 have hit them. The workaround it to just add a `*` anywhere you need to force a `deref` and it should work, but that's not truly seamless.

**Comment by tkaitchuck** [comment] 2020-09-03 23:27
I don't know the specifics of the `rust-gc` but it might be possible for them to implement:
```
impl<T> Finalize for Deref<Target = T> where T: Finalize {
    //...
}
```
That would take care of aHash and anything else doing trivial wrapping.

**Comment by tkaitchuck** [comment] 2020-10-28 03:35
Closing in favor of Manishearth/rust-gc#68

**Closed by tkaitchuck** 2020-10-28 03:35 UTC

**Comment by andersk** [comment] 2020-12-30 06:52
`impl<T> Finalize for Deref<Target = T> where T: Finalize` would be an implementation for the trait object (`dyn Deref`), which isn’t useful.

Perhaps `impl<T> Finalize for T where T: Deref, T::Target: Finalize` is the blanket implementation you meant, but that would conflict with every other implementation of `Finalize`.
