### ISSUE TITLE
did you test code?

### ISSUE THREAD

**Issue by zhuxiujia** [tkaitchuck/aHash#172] opened 2023-10-23 09:45 UTC
```log
error[E0423]: expected function, found macro `transmute`
   --> /Users/zxj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.4/src/operations.rs:128:15
    |
128 |         xor ^ transmute::<_, u128>(vaesmcq_u8(vaeseq_u8(value, transmute!(0u128))))
    |               ^^^^^^^^^^^^^^^^^^^^ not a function
    |
help: use `!` to invoke the macro
    |
128 |         xor ^ transmute::<_, u128>!(vaesmcq_u8(vaeseq_u8(value, transmute!(0u128))))
    |                                   +
help: consider importing one of these items instead
    |
1   + use core::mem::transmute;
    |
1   + use zerocopy::macro_util::core_reexport::mem::transmute;
    |


```

**Comment by PureWhiteWu** [comment] 2023-10-23 12:16
Seems duplicate of #170 .
This title is a bit too sharp, every author/maintainer of open source projects should be respected since this is all FREE OF CHARGE, and the code works fine on amd64.
I think this is just because the maintainer doesn't have an aarch64 machine to test it currently, and this is not a big deal.
Keep in mind that you must use open source code AT YOUR OWN RISK.

**Comment by joshlf** [comment] 2023-10-23 13:08
A fix has been uploaded: https://github.com/tkaitchuck/aHash/pull/171

**Comment by schungx** [comment] 2023-10-23 14:13
> This title is a bit too sharp

Agree.  And almost no info is provided as to O/S version, CPU etc.  The title is obnoxious.

**Comment by tkaitchuck** [comment] 2023-10-23 18:36
Fix published

**Closed by tkaitchuck** 2023-10-23 18:36 UTC

**Comment by zhuxiujia** [comment] 2023-10-25 03:15
> Seems duplicate of #170 . This title is a bit too sharp, every author/maintainer of open source projects should be respected since this is all FREE OF CHARGE, and the code works fine on amd64. I think this is just because the maintainer doesn't have an aarch64 machine to test it currently, and this is not a big deal. Keep in mind that you must use open source code AT YOUR OWN RISK.


I didn't make it clear that my device is arm64。
be sorry，Because this library has affected many library compilation failures， I hope the author can add more testing machines。 

Or use a more general implementation method, otherwise causing a large number of users to fail compilation will make people angry

**Comment by zhuxiujia** [comment] 2023-10-25 03:17
I strongly recommend that if there are significant changes, the version number should be modified instead of simply causing the existing version to fail compilation or worse things to happen

**Comment by schungx** [comment] 2023-10-25 03:36
> causing a large number of users to fail compilation will make people angry

In that case, I suggest that you keep your anger in control.  Remember that you're not paying any money for this.  This is free stuff and you have no right to be angry at a volunteer.

**Comment by PureWhiteWu** [comment] 2023-10-25 03:38
And also, if you are angry, you have the right to choose not to use open source projects. You can write it and maintain it by yourself.
