### ISSUE TITLE
test failure on s390x.

### ISSUE THREAD

**Issue by plugwash** [tkaitchuck/aHash#191] opened 2023-12-29 21:51 UTC
Debian CI disocvered that your crate has a test failure on s390x. I was able to log in to a Debian porterbox and reproduce the issue with the latest git version.

    ---- operations::test::test_add_length stdout ----
    thread 'operations::test::test_add_length' panicked at 'assertion failed: `(left == right)`
      left: `18446744073709551614`,
     right: `18446744073709551615`', src/operations.rs:369:9
    stack backtrace:
       0: rust_begin_unwind
                 at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
       1: core::panicking::panic_fmt
                 at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:67:14
       2: core::panicking::assert_failed_inner
       3: core::panicking::assert_failed
                 at /usr/src/rustc-1.70.0/library/core/src/panicking.rs:228:5
       4: ahash::operations::test::test_add_length
                 at ./src/operations.rs:369:9
       5: ahash::operations::test::test_add_length::{{closure}}
                 at ./src/operations.rs:366:26
       6: core::ops::function::FnOnce::call_once
                 at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5
       7: core::ops::function::FnOnce::call_once
                 at /usr/src/rustc-1.70.0/library/core/src/ops/function.rs:250:5

I would guess this is an endian issue somewhere but I'm not sure exactly where.

Any advice?

**Comment by jamessan** [comment] 2024-01-07 02:11
Duplicate of #152

**Closed** 2024-02-11 06:11 UTC
